/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitPROGRAM(PROGRAM *p) {} //abstract class

void PrintAbsyn::visitProgram(Program *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("program");
  visitIdent(p->ident_);
  render(".wosm;");
  _i_ = 0; p->vardecl_->accept(this);
  _i_ = 0; p->constdecl_->accept(this);
  _i_ = 0; p->funcdecl_->accept(this);
  _i_ = 0; p->blockprog_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVARDECL(VARDECL *p) {} //abstract class

void PrintAbsyn::visitVDecl(VDecl *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("var{");
  _i_ = 0; visitListVAR(p->listvar_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVDeclVoid(VDeclVoid *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVAR(VAR *p) {} //abstract class

void PrintAbsyn::visitVar(Var *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVarAssig(VarAssig *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->value_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVarV(VarV *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);
  render('[');
  visitInteger(p->integer_);
  render(']');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVarAssigV(VarAssigV *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);
  render('[');
  visitInteger(p->integer_);
  render("]=");
  _i_ = 0; p->value_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListVAR(ListVAR *listvar)
{
  iterListVAR(listvar->begin(), listvar->end());
}

void PrintAbsyn::iterListVAR(ListVAR::const_iterator i, ListVAR::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); render(';'); iterListVAR(i+1, j);
  }
}

void PrintAbsyn::visitTYPE(TYPE *p) {} //abstract class

void PrintAbsyn::visitTYPE_int(TYPE_int *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("int");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTYPE_double(TYPE_double *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("double");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTYPE_char(TYPE_char *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("char");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTYPEPOINTER(TYPEPOINTER *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->pointer_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPOINTER(POINTER *p) {} //abstract class

void PrintAbsyn::visitPointerInt(PointerInt *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("int");
  _i_ = 0; visitListAST(p->listast_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPointerDouble(PointerDouble *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("double");
  _i_ = 0; visitListAST(p->listast_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPointerChar(PointerChar *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("char");
  _i_ = 0; visitListAST(p->listast_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAST(AST *p) {} //abstract class

void PrintAbsyn::visitAst(Ast *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('*');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListAST(ListAST *listast)
{
  iterListAST(listast->begin(), listast->end());
}

void PrintAbsyn::iterListAST(ListAST::const_iterator i, ListAST::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListAST(i+1, j);
  }
}

void PrintAbsyn::visitCONSTDECL(CONSTDECL *p) {} //abstract class

void PrintAbsyn::visitCDecl(CDecl *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("const{");
  _i_ = 0; visitListCONST(p->listconst_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCDeclVoid(CDeclVoid *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCONST(CONST *p) {} //abstract class

void PrintAbsyn::visitConst(Const *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->value_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListCONST(ListCONST *listconst)
{
  iterListCONST(listconst->begin(), listconst->end());
}

void PrintAbsyn::iterListCONST(ListCONST::const_iterator i, ListCONST::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); render(';'); iterListCONST(i+1, j);
  }
}

void PrintAbsyn::visitVALUE(VALUE *p) {} //abstract class

void PrintAbsyn::visitVALUEInteger(VALUEInteger *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVALUEDouble(VALUEDouble *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitDouble(p->double_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVALUEEXP(VALUEEXP *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->exp_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFUNCDECL(FUNCDECL *p) {} //abstract class

void PrintAbsyn::visitFDecl(FDecl *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("function{");
  _i_ = 0; visitListFUNCTION(p->listfunction_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFDeclVoid(FDeclVoid *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFUNCTION(FUNCTION *p) {} //abstract class

void PrintAbsyn::visitFunction(Function *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->return_->accept(this);
  visitIdent(p->ident_);
  render("()");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFunctionP(FunctionP *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->return_->accept(this);
  visitIdent(p->ident_);
  render('(');
  _i_ = 0; visitListPARAM(p->listparam_);
  render(')');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListFUNCTION(ListFUNCTION *listfunction)
{
  iterListFUNCTION(listfunction->begin(), listfunction->end());
}

void PrintAbsyn::iterListFUNCTION(ListFUNCTION::const_iterator i, ListFUNCTION::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); render(';'); iterListFUNCTION(i+1, j);
  }
}

void PrintAbsyn::visitRETURN(RETURN *p) {} //abstract class

void PrintAbsyn::visitRETURN_int(RETURN_int *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("int");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRETURN_double(RETURN_double *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("double");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRETURN_char(RETURN_char *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("char");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRETURN_void(RETURN_void *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("void");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPARAM(PARAM *p) {} //abstract class

void PrintAbsyn::visitParam(Param *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListPARAM(ListPARAM *listparam)
{
  iterListPARAM(listparam->begin(), listparam->end());
}

void PrintAbsyn::iterListPARAM(ListPARAM::const_iterator i, ListPARAM::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListPARAM(i+1, j);
  }
}

void PrintAbsyn::visitBLOCKPROG(BLOCKPROG *p) {} //abstract class

void PrintAbsyn::visitBlockProg(BlockProg *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("begin");
  _i_ = 0; visitListCMD(p->listcmd_);
  render("end");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCMD(CMD *p) {} //abstract class

void PrintAbsyn::visitCMDIF(CMDIF *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->if_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCMDIFELSE(CMDIFELSE *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->ifelse_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCMDWHILE(CMDWHILE *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->while_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCMDFOR(CMDFOR *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->for_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCMDGOTO(CMDGOTO *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->goto_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCMDASSIGMENT(CMDASSIGMENT *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->assigment_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListCMD(ListCMD *listcmd)
{
  iterListCMD(listcmd->begin(), listcmd->end());
}

void PrintAbsyn::iterListCMD(ListCMD::const_iterator i, ListCMD::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListCMD(i+1, j);
  }
}

void PrintAbsyn::visitIF(IF *p) {} //abstract class

void PrintAbsyn::visitIf(If *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if(");
  _i_ = 0; p->cond_->accept(this);
  render("){");
  _i_ = 0; visitListCMD(p->listcmd_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIFELSE(IFELSE *p) {} //abstract class

void PrintAbsyn::visitIfElse(IfElse *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->if_->accept(this);
  render("else{");
  _i_ = 0; visitListCMD(p->listcmd_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitWHILE(WHILE *p) {} //abstract class

void PrintAbsyn::visitWhile(While *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("while(");
  _i_ = 0; p->cond_->accept(this);
  render("){");
  _i_ = 0; visitListCMD(p->listcmd_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFOR(FOR *p) {} //abstract class

void PrintAbsyn::visitFor(For *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("for(");
  _i_ = 0; p->assigment_->accept(this);
  _i_ = 0; p->cond_->accept(this);
  render(';');
  _i_ = 0; p->increment_->accept(this);
  render("){");
  _i_ = 0; visitListCMD(p->listcmd_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitGOTO(GOTO *p) {} //abstract class

void PrintAbsyn::visitGoto(Goto *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("goto");
  visitIdent(p->ident_);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASSIGMENT(ASSIGMENT *p) {} //abstract class

void PrintAbsyn::visitAssigment(Assigment *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->value_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAssigmentV(AssigmentV *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('[');
  visitInteger(p->integer_);
  render("]=");
  _i_ = 0; p->value_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitINCREMENT(INCREMENT *p) {} //abstract class

void PrintAbsyn::visitIncrement(Increment *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->value_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIncrementV(IncrementV *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCOND(COND *p) {} //abstract class

void PrintAbsyn::visitCond(Cond *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->logicexp_->accept(this);
  _i_ = 0; visitListLOGICEXP(p->listlogicexp_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLOGICOP(LOGICOP *p) {} //abstract class

void PrintAbsyn::visitLOGICOP1(LOGICOP1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('<');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLOGICOP2(LOGICOP2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("<=");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLOGICOP3(LOGICOP3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("==");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLOGICOP4(LOGICOP4 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("!=");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLOGICOP5(LOGICOP5 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render(">=");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLOGICOP6(LOGICOP6 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('>');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLOGICOP7(LOGICOP7 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("&&");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLOGICOP8(LOGICOP8 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("||");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLOGICEXP(LOGICEXP *p) {} //abstract class

void PrintAbsyn::visitLogicExp(LogicExp *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->value_1->accept(this);
  _i_ = 0; p->logicop_->accept(this);
  _i_ = 0; p->value_2->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListLOGICEXP(ListLOGICEXP *listlogicexp)
{
  iterListLOGICEXP(listlogicexp->begin(), listlogicexp->end());
}

void PrintAbsyn::iterListLOGICEXP(ListLOGICEXP::const_iterator i, ListLOGICEXP::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render("&&"); iterListLOGICEXP(i+1, j);
  }
}

void PrintAbsyn::visitEXP(EXP *p) {} //abstract class

void PrintAbsyn::visitExp(Exp *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->aritexp_->accept(this);
  _i_ = 0; visitListARITEXP(p->listaritexp_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitARITOP(ARITOP *p) {} //abstract class

void PrintAbsyn::visitARITOP1(ARITOP1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('+');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitARITOP2(ARITOP2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('-');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitARITOP3(ARITOP3 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('*');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitARITOP4(ARITOP4 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('/');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitARITEXP(ARITEXP *p) {} //abstract class

void PrintAbsyn::visitAritExp(AritExp *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->value_1->accept(this);
  _i_ = 0; p->aritop_->accept(this);
  _i_ = 0; p->value_2->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListARITEXP(ListARITEXP *listaritexp)
{
  iterListARITEXP(listaritexp->begin(), listaritexp->end());
}

void PrintAbsyn::iterListARITEXP(ListARITEXP::const_iterator i, ListARITEXP::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render('+'); iterListARITEXP(i+1, j);
  }
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitPROGRAM(PROGRAM *p) {} //abstract class

void ShowAbsyn::visitProgram(Program *p)
{
  bufAppend('(');
  bufAppend("Program");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->vardecl_)  p->vardecl_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->constdecl_)  p->constdecl_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->funcdecl_)  p->funcdecl_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blockprog_)  p->blockprog_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVARDECL(VARDECL *p) {} //abstract class

void ShowAbsyn::visitVDecl(VDecl *p)
{
  bufAppend('(');
  bufAppend("VDecl");
  bufAppend(' ');
  bufAppend('[');
  if (p->listvar_)  p->listvar_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitVDeclVoid(VDeclVoid *p)
{
  bufAppend("VDeclVoid");
}
void ShowAbsyn::visitVAR(VAR *p) {} //abstract class

void ShowAbsyn::visitVar(Var *p)
{
  bufAppend('(');
  bufAppend("Var");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitVarAssig(VarAssig *p)
{
  bufAppend('(');
  bufAppend("VarAssig");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVarV(VarV *p)
{
  bufAppend('(');
  bufAppend("VarV");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitVarAssigV(VarAssigV *p)
{
  bufAppend('(');
  bufAppend("VarAssigV");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListVAR(ListVAR *listvar)
{
  for (ListVAR::const_iterator i = listvar->begin() ; i != listvar->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listvar->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitTYPE(TYPE *p) {} //abstract class

void ShowAbsyn::visitTYPE_int(TYPE_int *p)
{
  bufAppend("TYPE_int");
}
void ShowAbsyn::visitTYPE_double(TYPE_double *p)
{
  bufAppend("TYPE_double");
}
void ShowAbsyn::visitTYPE_char(TYPE_char *p)
{
  bufAppend("TYPE_char");
}
void ShowAbsyn::visitTYPEPOINTER(TYPEPOINTER *p)
{
  bufAppend('(');
  bufAppend("TYPEPOINTER");
  bufAppend(' ');
  bufAppend('[');
  if (p->pointer_)  p->pointer_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitPOINTER(POINTER *p) {} //abstract class

void ShowAbsyn::visitPointerInt(PointerInt *p)
{
  bufAppend('(');
  bufAppend("PointerInt");
  bufAppend(' ');
  bufAppend('[');
  if (p->listast_)  p->listast_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitPointerDouble(PointerDouble *p)
{
  bufAppend('(');
  bufAppend("PointerDouble");
  bufAppend(' ');
  bufAppend('[');
  if (p->listast_)  p->listast_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitPointerChar(PointerChar *p)
{
  bufAppend('(');
  bufAppend("PointerChar");
  bufAppend(' ');
  bufAppend('[');
  if (p->listast_)  p->listast_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAST(AST *p) {} //abstract class

void ShowAbsyn::visitAst(Ast *p)
{
  bufAppend("Ast");
}
void ShowAbsyn::visitListAST(ListAST *listast)
{
  for (ListAST::const_iterator i = listast->begin() ; i != listast->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listast->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitCONSTDECL(CONSTDECL *p) {} //abstract class

void ShowAbsyn::visitCDecl(CDecl *p)
{
  bufAppend('(');
  bufAppend("CDecl");
  bufAppend(' ');
  bufAppend('[');
  if (p->listconst_)  p->listconst_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitCDeclVoid(CDeclVoid *p)
{
  bufAppend("CDeclVoid");
}
void ShowAbsyn::visitCONST(CONST *p) {} //abstract class

void ShowAbsyn::visitConst(Const *p)
{
  bufAppend('(');
  bufAppend("Const");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListCONST(ListCONST *listconst)
{
  for (ListCONST::const_iterator i = listconst->begin() ; i != listconst->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listconst->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitVALUE(VALUE *p) {} //abstract class

void ShowAbsyn::visitVALUEInteger(VALUEInteger *p)
{
  bufAppend('(');
  bufAppend("VALUEInteger");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitVALUEDouble(VALUEDouble *p)
{
  bufAppend('(');
  bufAppend("VALUEDouble");
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitVALUEEXP(VALUEEXP *p)
{
  bufAppend('(');
  bufAppend("VALUEEXP");
  bufAppend(' ');
  bufAppend('[');
  if (p->exp_)  p->exp_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFUNCDECL(FUNCDECL *p) {} //abstract class

void ShowAbsyn::visitFDecl(FDecl *p)
{
  bufAppend('(');
  bufAppend("FDecl");
  bufAppend(' ');
  bufAppend('[');
  if (p->listfunction_)  p->listfunction_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitFDeclVoid(FDeclVoid *p)
{
  bufAppend("FDeclVoid");
}
void ShowAbsyn::visitFUNCTION(FUNCTION *p) {} //abstract class

void ShowAbsyn::visitFunction(Function *p)
{
  bufAppend('(');
  bufAppend("Function");
  bufAppend(' ');
  bufAppend('[');
  if (p->return_)  p->return_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitFunctionP(FunctionP *p)
{
  bufAppend('(');
  bufAppend("FunctionP");
  bufAppend(' ');
  bufAppend('[');
  if (p->return_)  p->return_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listparam_)  p->listparam_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListFUNCTION(ListFUNCTION *listfunction)
{
  for (ListFUNCTION::const_iterator i = listfunction->begin() ; i != listfunction->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listfunction->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitRETURN(RETURN *p) {} //abstract class

void ShowAbsyn::visitRETURN_int(RETURN_int *p)
{
  bufAppend("RETURN_int");
}
void ShowAbsyn::visitRETURN_double(RETURN_double *p)
{
  bufAppend("RETURN_double");
}
void ShowAbsyn::visitRETURN_char(RETURN_char *p)
{
  bufAppend("RETURN_char");
}
void ShowAbsyn::visitRETURN_void(RETURN_void *p)
{
  bufAppend("RETURN_void");
}
void ShowAbsyn::visitPARAM(PARAM *p) {} //abstract class

void ShowAbsyn::visitParam(Param *p)
{
  bufAppend('(');
  bufAppend("Param");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitListPARAM(ListPARAM *listparam)
{
  for (ListPARAM::const_iterator i = listparam->begin() ; i != listparam->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listparam->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitBLOCKPROG(BLOCKPROG *p) {} //abstract class

void ShowAbsyn::visitBlockProg(BlockProg *p)
{
  bufAppend('(');
  bufAppend("BlockProg");
  bufAppend(' ');
  bufAppend('[');
  if (p->listcmd_)  p->listcmd_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitCMD(CMD *p) {} //abstract class

void ShowAbsyn::visitCMDIF(CMDIF *p)
{
  bufAppend('(');
  bufAppend("CMDIF");
  bufAppend(' ');
  bufAppend('[');
  if (p->if_)  p->if_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitCMDIFELSE(CMDIFELSE *p)
{
  bufAppend('(');
  bufAppend("CMDIFELSE");
  bufAppend(' ');
  bufAppend('[');
  if (p->ifelse_)  p->ifelse_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitCMDWHILE(CMDWHILE *p)
{
  bufAppend('(');
  bufAppend("CMDWHILE");
  bufAppend(' ');
  bufAppend('[');
  if (p->while_)  p->while_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitCMDFOR(CMDFOR *p)
{
  bufAppend('(');
  bufAppend("CMDFOR");
  bufAppend(' ');
  bufAppend('[');
  if (p->for_)  p->for_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitCMDGOTO(CMDGOTO *p)
{
  bufAppend('(');
  bufAppend("CMDGOTO");
  bufAppend(' ');
  bufAppend('[');
  if (p->goto_)  p->goto_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitCMDASSIGMENT(CMDASSIGMENT *p)
{
  bufAppend('(');
  bufAppend("CMDASSIGMENT");
  bufAppend(' ');
  bufAppend('[');
  if (p->assigment_)  p->assigment_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListCMD(ListCMD *listcmd)
{
  for (ListCMD::const_iterator i = listcmd->begin() ; i != listcmd->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listcmd->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitIF(IF *p) {} //abstract class

void ShowAbsyn::visitIf(If *p)
{
  bufAppend('(');
  bufAppend("If");
  bufAppend(' ');
  bufAppend('[');
  if (p->cond_)  p->cond_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listcmd_)  p->listcmd_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitIFELSE(IFELSE *p) {} //abstract class

void ShowAbsyn::visitIfElse(IfElse *p)
{
  bufAppend('(');
  bufAppend("IfElse");
  bufAppend(' ');
  bufAppend('[');
  if (p->if_)  p->if_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listcmd_)  p->listcmd_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitWHILE(WHILE *p) {} //abstract class

void ShowAbsyn::visitWhile(While *p)
{
  bufAppend('(');
  bufAppend("While");
  bufAppend(' ');
  bufAppend('[');
  if (p->cond_)  p->cond_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listcmd_)  p->listcmd_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitFOR(FOR *p) {} //abstract class

void ShowAbsyn::visitFor(For *p)
{
  bufAppend('(');
  bufAppend("For");
  bufAppend(' ');
  bufAppend('[');
  if (p->assigment_)  p->assigment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->cond_)  p->cond_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->increment_)  p->increment_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listcmd_)  p->listcmd_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitGOTO(GOTO *p) {} //abstract class

void ShowAbsyn::visitGoto(Goto *p)
{
  bufAppend('(');
  bufAppend("Goto");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitASSIGMENT(ASSIGMENT *p) {} //abstract class

void ShowAbsyn::visitAssigment(Assigment *p)
{
  bufAppend('(');
  bufAppend("Assigment");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitAssigmentV(AssigmentV *p)
{
  bufAppend('(');
  bufAppend("AssigmentV");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitINCREMENT(INCREMENT *p) {} //abstract class

void ShowAbsyn::visitIncrement(Increment *p)
{
  bufAppend('(');
  bufAppend("Increment");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->value_)  p->value_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitIncrementV(IncrementV *p)
{
  bufAppend("IncrementV");
}
void ShowAbsyn::visitCOND(COND *p) {} //abstract class

void ShowAbsyn::visitCond(Cond *p)
{
  bufAppend('(');
  bufAppend("Cond");
  bufAppend(' ');
  bufAppend('[');
  if (p->logicexp_)  p->logicexp_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listlogicexp_)  p->listlogicexp_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitLOGICOP(LOGICOP *p) {} //abstract class

void ShowAbsyn::visitLOGICOP1(LOGICOP1 *p)
{
  bufAppend("LOGICOP1");
}
void ShowAbsyn::visitLOGICOP2(LOGICOP2 *p)
{
  bufAppend("LOGICOP2");
}
void ShowAbsyn::visitLOGICOP3(LOGICOP3 *p)
{
  bufAppend("LOGICOP3");
}
void ShowAbsyn::visitLOGICOP4(LOGICOP4 *p)
{
  bufAppend("LOGICOP4");
}
void ShowAbsyn::visitLOGICOP5(LOGICOP5 *p)
{
  bufAppend("LOGICOP5");
}
void ShowAbsyn::visitLOGICOP6(LOGICOP6 *p)
{
  bufAppend("LOGICOP6");
}
void ShowAbsyn::visitLOGICOP7(LOGICOP7 *p)
{
  bufAppend("LOGICOP7");
}
void ShowAbsyn::visitLOGICOP8(LOGICOP8 *p)
{
  bufAppend("LOGICOP8");
}
void ShowAbsyn::visitLOGICEXP(LOGICEXP *p) {} //abstract class

void ShowAbsyn::visitLogicExp(LogicExp *p)
{
  bufAppend('(');
  bufAppend("LogicExp");
  bufAppend(' ');
  p->value_1->accept(this);
  bufAppend(' ');
  bufAppend('[');
  if (p->logicop_)  p->logicop_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->value_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitListLOGICEXP(ListLOGICEXP *listlogicexp)
{
  for (ListLOGICEXP::const_iterator i = listlogicexp->begin() ; i != listlogicexp->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listlogicexp->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitEXP(EXP *p) {} //abstract class

void ShowAbsyn::visitExp(Exp *p)
{
  bufAppend('(');
  bufAppend("Exp");
  bufAppend(' ');
  bufAppend('[');
  if (p->aritexp_)  p->aritexp_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listaritexp_)  p->listaritexp_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitARITOP(ARITOP *p) {} //abstract class

void ShowAbsyn::visitARITOP1(ARITOP1 *p)
{
  bufAppend("ARITOP1");
}
void ShowAbsyn::visitARITOP2(ARITOP2 *p)
{
  bufAppend("ARITOP2");
}
void ShowAbsyn::visitARITOP3(ARITOP3 *p)
{
  bufAppend("ARITOP3");
}
void ShowAbsyn::visitARITOP4(ARITOP4 *p)
{
  bufAppend("ARITOP4");
}
void ShowAbsyn::visitARITEXP(ARITEXP *p) {} //abstract class

void ShowAbsyn::visitAritExp(AritExp *p)
{
  bufAppend('(');
  bufAppend("AritExp");
  bufAppend(' ');
  p->value_1->accept(this);
  bufAppend(' ');
  bufAppend('[');
  if (p->aritop_)  p->aritop_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->value_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitListARITEXP(ListARITEXP *listaritexp)
{
  for (ListARITEXP::const_iterator i = listaritexp->begin() ; i != listaritexp->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listaritexp->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


